Try to not waste clicks or rotation
t3knomanzer/maxmix-software pull request #146
Opened 2020-08-25 18:43 UTC by quadbyte

## Description
There was a little something which had been bugging me for a while : the first interaction on the knob was used to awake the display but no action was registered.  It meant that double clicking on the knob was ignored when the display was asleep. So I ended up having to do 2x double clicks to mute the currently selected item.

I changed it so we don't waste user inputs. Sometimes people want to interact with the device without looking at the LCD.

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] Requested changes are in a branch
- [x] Compiled and tested requested changes on target hardware (PC, device)

2020-08-26 21:07 UTC, t3knomanzer commented
So this behavior was actually by design. Users complained about the opposite and that's why we implemented it. The concern was that when the device was asleep, input was triggering actions without knowing what those were.

So that means some people want it some other don't... therefore it should probably be exposed as a setting?

2020-08-27 04:02 UTC, SchemingWeasels commented
I can understand the annoyance for double clicking, because it's suppose to
mute the device. Perhaps we can put an exception for double clicks to
bypass the wake rejection?

After all, if you are just waking the device you wouldn't double click. It
would have to be intentional.

On Thu, Aug 27, 2020, 5:08 AM Ruben Henares <notifications@github.com>
wrote:

> So this behavior was actually by design. Users complained about the
> opposite and that's why we implemented it. The concern was that when the
> device was asleep, input was triggering actions without knowing what those
> were.
>
> So that means some people want it some other don't... therefore it should
> probably be exposed as a setting?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/t3knomanzer/maxmix-software/pull/146#issuecomment-681124649>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABHOWRCPRMB7LRE7COLJ7DTSCV2TFANCNFSM4QK672DA>
> .
>

2020-08-27 04:19 UTC, t3knomanzer commented
That makes sense but I’m wondering if it may make things confusing. 
What do you guys think, should we expose ignoring the input to wake as a setting or should we just create an exception for double tap?

@SchemingWeasels btw we now have a discord server if you want to join. 

That doesn’t replace GitHub issues and conversations related to issues should still happen in GitHub. But it may be handy for general discussions and other things. 

https://discord.gg/n8vM5N

2020-08-27 16:02 UTC, SchemingWeasels commented
My opinion is that we put in an exception for double-taps, but of course, I'm heavily biased because I was the one that found the initial input to be annoying :sweat_smile:

2020-08-27 16:40 UTC, quadbyte commented
I agree with @SchemingWeasels. I implemented this change because I didn't like to have to quadruple click to get a mute/unmute.
For the other actions I guess it's ok to only awake the display on the first input.

Also from my experience exposing too many settings to the users can become an issue in the long run.

2020-08-27 17:38 UTC, t3knomanzer commented
Let me test it real quick

2020-08-27 17:46 UTC, SchemingWeasels requested changes
It is still registering rotations right? Discard everything except the double click.

2020-08-27 17:52 UTC, t3knomanzer commented
I was going to say just that :D

2020-08-27 17:55 UTC, quadbyte commented
Maybe my english is broken :)   The behavior is as usual but if a double tap is detected and the display is asleep, it awake the display and register the mute/unmute.

2020-08-27 17:58 UTC, SchemingWeasels commented
> Maybe my english is broken :) The behavior is as usual but if a double tap is detected and the display is asleep, it awake the display and register the mute/unmute.

Yup but can you add back in the code to make the other actions only wake the device?

2020-08-27 17:59 UTC, quadbyte commented
I did it (with minor changes) with commit 11662d2

2020-08-27 18:05 UTC, SchemingWeasels requested changes
Check these lines out. Let me know if it's still confusing

2020-08-27 18:05 UTC, SchemingWeasels commented on Embedded/MaxMix/MaxMix.ino
>    if(mode == MODE_MASTER)
You'll need to put this back or else rotations will register

2020-08-27 18:05 UTC, SchemingWeasels commented on Embedded/MaxMix/MaxMix.ino
> +    }
This is redundant right? It's checked on top already in line 438

2020-08-27 18:07 UTC, quadbyte commented
Ok, I see, something got screwed or badly merged at some point. Gotta go for a few hours. will fix everything when I get back. Sorry for the trouble !

2020-08-27 20:13 UTC, quadbyte commented
It's been a long day, committed a fix, hope it is okay now :)

2020-08-27 20:31 UTC, t3knomanzer commented
Thank you guys!

2020-08-27 20:31 UTC, merged